// Copyright (c) 2018 RISC Software GmbH
//
// This file was generated by CPACSGen from CPACS XML Schema (c) German Aerospace Center (DLR/SC).
// Do not edit, all changes are lost when files are re-generated.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <boost/optional.hpp>
#include <boost/utility/in_place_factory.hpp>
#include <string>
#include <tixi.h>
#include "tigl_internal.h"

namespace tigl
{
namespace generated
{
    // This class is used in:
    // generated from /xsd:schema/xsd:complexType[1]
    class CPACSRoot
    {
    public:
        TIGL_EXPORT CPACSRoot();
        TIGL_EXPORT virtual ~CPACSRoot();

        TIGL_EXPORT virtual void ReadCPACS(const TixiDocumentHandle& tixiHandle, const std::string& xpath);
        TIGL_EXPORT virtual void WriteCPACS(const TixiDocumentHandle& tixiHandle, const std::string& xpath) const;

        TIGL_EXPORT virtual const boost::optional<int>& GetA() const;
        TIGL_EXPORT virtual void SetA(const boost::optional<int>& value);

        TIGL_EXPORT virtual const boost::optional<int>& GetB() const;
        TIGL_EXPORT virtual void SetB(const boost::optional<int>& value);

        TIGL_EXPORT virtual const boost::optional<int>& GetC() const;
        TIGL_EXPORT virtual void SetC(const boost::optional<int>& value);

        TIGL_EXPORT virtual const boost::optional<int>& GetD() const;
        TIGL_EXPORT virtual void SetD(const boost::optional<int>& value);

        TIGL_EXPORT virtual const boost::optional<int>& GetE() const;
        TIGL_EXPORT virtual void SetE(const boost::optional<int>& value);

        TIGL_EXPORT virtual const boost::optional<int>& GetF() const;
        TIGL_EXPORT virtual void SetF(const boost::optional<int>& value);

    protected:
        boost::optional<int> m_a;
        boost::optional<int> m_b;
        boost::optional<int> m_c;
        boost::optional<int> m_d;
        boost::optional<int> m_e;
        boost::optional<int> m_f;

    private:
#ifdef HAVE_CPP11
        CPACSRoot(const CPACSRoot&) = delete;
        CPACSRoot& operator=(const CPACSRoot&) = delete;

        CPACSRoot(CPACSRoot&&) = delete;
        CPACSRoot& operator=(CPACSRoot&&) = delete;
#else
        CPACSRoot(const CPACSRoot&);
        CPACSRoot& operator=(const CPACSRoot&);
#endif
    };
} // namespace generated

// Aliases in tigl namespace
#ifdef HAVE_CPP11
using CCPACSRoot = generated::CPACSRoot;
#else
typedef generated::CPACSRoot CCPACSRoot;
#endif
} // namespace tigl
// Copyright (c) 2018 RISC Software GmbH
//
// This file was generated by CPACSGen from CPACS XML Schema (c) German Aerospace Center (DLR/SC).
// Do not edit, all changes are lost when files are re-generated.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "CPACSRoot.h"
#include "CTiglError.h"
#include "CTiglLogging.h"
#include "TixiHelper.h"

namespace tigl
{
namespace generated
{
    CPACSRoot::CPACSRoot()
    {
    }

    CPACSRoot::~CPACSRoot()
    {
    }

    void CPACSRoot::ReadCPACS(const TixiDocumentHandle& tixiHandle, const std::string& xpath)
    {
        // read element a
        if (tixi::TixiCheckElement(tixiHandle, xpath + "/a")) {
            m_a = tixi::TixiGetElement<int>(tixiHandle, xpath + "/a");
        }

        // read element b
        if (tixi::TixiCheckElement(tixiHandle, xpath + "/b")) {
            m_b = tixi::TixiGetElement<int>(tixiHandle, xpath + "/b");
        }

        // read element c
        if (tixi::TixiCheckElement(tixiHandle, xpath + "/c")) {
            m_c = tixi::TixiGetElement<int>(tixiHandle, xpath + "/c");
        }

        // read element d
        if (tixi::TixiCheckElement(tixiHandle, xpath + "/d")) {
            m_d = tixi::TixiGetElement<int>(tixiHandle, xpath + "/d");
        }

        // read element e
        if (tixi::TixiCheckElement(tixiHandle, xpath + "/e")) {
            m_e = tixi::TixiGetElement<int>(tixiHandle, xpath + "/e");
        }

        // read element f
        if (tixi::TixiCheckElement(tixiHandle, xpath + "/f")) {
            m_f = tixi::TixiGetElement<int>(tixiHandle, xpath + "/f");
        }

    }

    void CPACSRoot::WriteCPACS(const TixiDocumentHandle& tixiHandle, const std::string& xpath) const
    {
        // write element a
        if (m_a) {
            tixi::TixiCreateElementIfNotExists(tixiHandle, xpath + "/a");
            tixi::TixiSaveElement(tixiHandle, xpath + "/a", *m_a);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/a")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/a");
            }
        }

        // write element b
        if (m_b) {
            tixi::TixiCreateElementIfNotExists(tixiHandle, xpath + "/b");
            tixi::TixiSaveElement(tixiHandle, xpath + "/b", *m_b);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/b")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/b");
            }
        }

        // write element c
        if (m_c) {
            tixi::TixiCreateElementIfNotExists(tixiHandle, xpath + "/c");
            tixi::TixiSaveElement(tixiHandle, xpath + "/c", *m_c);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/c")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/c");
            }
        }

        // write element d
        if (m_d) {
            tixi::TixiCreateElementIfNotExists(tixiHandle, xpath + "/d");
            tixi::TixiSaveElement(tixiHandle, xpath + "/d", *m_d);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/d")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/d");
            }
        }

        // write element e
        if (m_e) {
            tixi::TixiCreateElementIfNotExists(tixiHandle, xpath + "/e");
            tixi::TixiSaveElement(tixiHandle, xpath + "/e", *m_e);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/e")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/e");
            }
        }

        // write element f
        if (m_f) {
            tixi::TixiCreateElementIfNotExists(tixiHandle, xpath + "/f");
            tixi::TixiSaveElement(tixiHandle, xpath + "/f", *m_f);
        }
        else {
            if (tixi::TixiCheckElement(tixiHandle, xpath + "/f")) {
                tixi::TixiRemoveElement(tixiHandle, xpath + "/f");
            }
        }

    }

    const boost::optional<int>& CPACSRoot::GetA() const
    {
        return m_a;
    }

    void CPACSRoot::SetA(const boost::optional<int>& value)
    {
        m_a = value;
    }

    const boost::optional<int>& CPACSRoot::GetB() const
    {
        return m_b;
    }

    void CPACSRoot::SetB(const boost::optional<int>& value)
    {
        m_b = value;
    }

    const boost::optional<int>& CPACSRoot::GetC() const
    {
        return m_c;
    }

    void CPACSRoot::SetC(const boost::optional<int>& value)
    {
        m_c = value;
    }

    const boost::optional<int>& CPACSRoot::GetD() const
    {
        return m_d;
    }

    void CPACSRoot::SetD(const boost::optional<int>& value)
    {
        m_d = value;
    }

    const boost::optional<int>& CPACSRoot::GetE() const
    {
        return m_e;
    }

    void CPACSRoot::SetE(const boost::optional<int>& value)
    {
        m_e = value;
    }

    const boost::optional<int>& CPACSRoot::GetF() const
    {
        return m_f;
    }

    void CPACSRoot::SetF(const boost::optional<int>& value)
    {
        m_f = value;
    }

} // namespace generated
} // namespace tigl
